services:
  db:
    image: postgres:15
    container_name: Next-Planner-PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: ["postgres", "-c", "port=${POSTGRES_PORT}"]
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: Next-Planner-Redis
    restart: always
    environment:
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["redis-server", "--port", "${REDIS_PORT}"]
    volumes:
      - redis-data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Next-Planner-Backend
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
    depends_on:
      - db
      - redis
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${BACKEND_PORT}", "--reload"]
    volumes:
      - ./backend:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Next-Planner-Frontend
    env_file:
      - ./.env
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
      CHOKIDAR_INTERVAL: ${CHOKIDAR_INTERVAL}
      NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: ["npm", "run", "dev", "--", "-H", "0.0.0.0", "-p", "${FRONTEND_PORT}"]
    volumes:
      - ./frontend:/usr/src/app
      - frontend-node-modules:/usr/src/app/node_modules
    working_dir: /usr/src/app

volumes:
  db-data:
  redis-data:
  frontend-node-modules:
